### PR TITLE
Make main-header positioning relative

### PR DESCRIPTION
**Pull request by natejacobson**

### CODE REVIEW

**Comment by natejacobson** [comment]
Hmmm. Now that I don't understand. One file?

**Comment by jeremyfelt** [comment]
Should this still be open or did you get it through on another commit?

**Comment by natejacobson** [comment]
I haven't managed to merge this in yet. Need to figure out how to do so.

**Comment by jeremyfelt** [comment]
I think I screwed it up worse trying to rebase it.

It may be worth just doing a new branch. Or - if you can point out the bits that should change, let me know and I can tweak it line by line.

**Comment by jeremyfelt** [comment]
This got out of whack and the original purpose isn't clear so I'm going to close it out.

**Pull request closed without merging**
