### PR TITLE
[PR] Allow section headers as H5 elements

### PR DESCRIPTION
**Pull request by jeremyfelt**

### CODE REVIEW

**Comment by jeremyfelt** [comment]
@philcable #reviewmerge?

**Comment by jeremyfelt** [comment]
@philcable Good catch, thanks! #reviewmerge second round :)

**Comment by philcable** [comment]
There was one other array that h5 needed to be added to, so I just added it :)

**Comment by jeremyfelt** [comment]
Oh wow. I did a great job at testing this. :8ball: Thanks!

**Pull request merged**
